title: Reffs
tagline: Verified referral codes
description: > # this means to ignore newlines until "baseurl:"
  Reffs — Refferal codes for Doordash and more.
baseurl: ""
url: "http://reffs.co/"
markdown: kramdown
